added logging; added checks to 'stop' script

diff --git a/bash/stop b/bash/stop
--- a/bash/stop
+++ b/bash/stop
@@ -1,3 +1,18 @@
 #!/usr/bin/env bash
-kill $(pgrep -f initialize)
-kill $(pgrep -f server-control)
+logd=/var/log/servinit
+pgrep -f initialize > /dev/null
+if [ $? -eq 0 ]
+then
+  kill $(pgrep -f initialize) 2>>$logd\/errors.log >> $logd\/standard.log
+  echo "Initialize script has been stopped" 2>>$logd\/errors.log >> $logd\/standard.log
+else
+  echo "Initialize script not running" 2>>$logd\/errors.log >> $logd\/standard.log
+fi
+pgrep -f server-control > /dev/null
+if [ $? -eq 0 ]
+then
+  kill $(pgrep -f server-control) 2>>$logd\/errors.log >> $logd\/standard.log
+  echo "Server control script has been stopped" 2>>$logd\/errors.log >> $logd\/standard.log
+else
+  echo "Server control script not running" 2>>$logd\/errors.log >> $logd\/standard.log
+fi
